### ISSUE TITLE
Put installation prerequisites in docs

### ISSUE THREAD

**Issue by jcs224** [bozemanlaravel/meetup#13]
PHP, Composer, maybe Homestead or Valet

**Comment by gleman17** [comment]
How about a docker container?  Be pretty cool to just upload an image for the world to have.

**Comment by jcs224** [comment]
@gleman17 That would be slick!

**Comment by jcs224** [comment]
Well now Laravel Sail is a thing, so it's been included in the project but needs to be documented.

**Comment by jcs224** [comment]
Documented.
